<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12652" started-at="2018-12-22T16:01:14Z" finished-at="2018-12-22T16:01:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12652" started-at="2018-12-22T16:01:14Z" finished-at="2018-12-22T16:01:27Z">
      <class name="udemy.rahul.Assignment1Chk">
        <test-method status="PASS" signature="manageDriver()[pri:0, instance:udemy.rahul.Assignment1Chk@71e7a66b]" name="manageDriver" is-config="true" duration-ms="12470" started-at="2018-12-22T21:31:14Z" finished-at="2018-12-22T21:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- manageDriver -->
        <test-method status="PASS" signature="checkBoxEnabledTest()[pri:0, instance:udemy.rahul.Assignment1Chk@71e7a66b]" name="checkBoxEnabledTest" duration-ms="43" started-at="2018-12-22T21:31:27Z" finished-at="2018-12-22T21:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkBoxEnabledTest -->
        <test-method status="PASS" signature="checkBoxSelectTest()[pri:0, instance:udemy.rahul.Assignment1Chk@71e7a66b]" name="checkBoxSelectTest" duration-ms="80" started-at="2018-12-22T21:31:27Z" finished-at="2018-12-22T21:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkBoxSelectTest -->
        <test-method status="PASS" signature="checkBoxSelectvalidationTest()[pri:0, instance:udemy.rahul.Assignment1Chk@71e7a66b]" name="checkBoxSelectvalidationTest" duration-ms="19" started-at="2018-12-22T21:31:27Z" finished-at="2018-12-22T21:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkBoxSelectvalidationTest -->
        <test-method status="FAIL" signature="checkBoxisSelectedTest()[pri:0, instance:udemy.rahul.Assignment1Chk@71e7a66b]" name="checkBoxisSelectedTest" duration-ms="14" started-at="2018-12-22T21:31:27Z" finished-at="2018-12-22T21:31:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at udemy.rahul.Assignment1Chk.checkBoxisSelectedTest(Assignment1Chk.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkBoxisSelectedTest -->
        <test-method status="PASS" signature="closeAllResource()[pri:0, instance:udemy.rahul.Assignment1Chk@71e7a66b]" name="closeAllResource" is-config="true" duration-ms="0" started-at="2018-12-22T21:31:27Z" finished-at="2018-12-22T21:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAllResource -->
      </class> <!-- udemy.rahul.Assignment1Chk -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
